### ISSUE TITLE
High-level context

### ISSUE THREAD

**Issue by anakngcoder** [Bo0m21/Converter#2]
Hi, I've been looking for a VCE converter/player that is free to use. I must admit that I am a novice coder and needs high-level context on how your code works. It's been 2 years now since this was published and I wonder if this still works today. I appreciate your support. Thanks.

**Comment by sneklyudov** [comment]
Hi friend, I can say that it works with the data that I provided. We read the file completely and parse it if there is a certain key, and then distribute it by questions and answers.

You can fork it and finish it if you want, unfortunately I will not finish anything.

**Comment by anakngcoder** [comment]
Thank you for your response. Can i request for simple instructions on how to make this app work or at least a high level context how this works?

**Comment by sneklyudov** [comment]
Anyone with basic knowledge will be able to run this application. Unfortunately, I will not write instructions for you.

**Comment by anakngcoder** [comment]
Understood. Thank you.
